from __future__ import annotations

from io import BytesIO
from pathlib import Path

import pandas as pd
import pytest

from src.analytics import ai_risk_intelligence
from src.agent import run_query_plan
from src.database import DriftDatabase, replace_applications_rows
from src.spreadsheet_import import (
    SpreadsheetImportError,
    import_excel_workbook,
    list_excel_sheets,
    preview_excel_workbook,
)


def _workbook_bytes(sheets: dict[str, pd.DataFrame]) -> bytes:
    buffer = BytesIO()
    with pd.ExcelWriter(buffer, engine="openpyxl") as writer:
        for sheet_name, frame in sheets.items():
            frame.to_excel(writer, index=False, sheet_name=sheet_name)
    return buffer.getvalue()


def _csv_bytes(frame: pd.DataFrame) -> bytes:
    return frame.to_csv(index=False).encode("utf-8")


def _valid_frame(app_id: str, app_name: str, product: str) -> pd.DataFrame:
    return pd.DataFrame(
        [
            {
                "Application ID": app_id,
                "Application Name": app_name,
                "Product": product,
                "Data Center": "DAL-1",
                "Approved Version": "10.2",
                "Detected Version": "10.0",
                "RTO Score": 2,
                "Status": "Open",
                "Exemption Requested": "No",
                "In Scope": "Yes",
                "Drift Detected On": "2026-01-15",
            }
        ]
    )


def test_imports_multiple_sheets_and_normalizes_aliases() -> None:
    workbook = _workbook_bytes(
        {
            "Payments": _valid_frame("APP-900", "Treasury Gateway", "Payments"),
            "Risk": _valid_frame("APP-901", "Risk Console", "Risk"),
        }
    )

    assert list_excel_sheets(workbook) == ["Payments", "Risk"]
    result = import_excel_workbook(workbook, selected_sheets=["Payments", "Risk"], filename="drift.xlsx")

    assert result.row_count == 2
    assert result.sheets == ["Payments", "Risk"]
    assert result.rows[0]["app_id"] == "APP-900"
    assert result.rows[0]["business_owner"] == "Unassigned"
    assert result.rows[0]["exemption_requested"] == "N"
    assert result.rows[0]["in_scope"] == "Y"


def test_spreadsheet_import_reports_missing_required_columns() -> None:
    workbook = _workbook_bytes({"BadSheet": pd.DataFrame([{"Application ID": "APP-1"}])})

    with pytest.raises(SpreadsheetImportError) as exc_info:
        import_excel_workbook(workbook, selected_sheets=["BadSheet"])

    assert "Missing essential columns" in str(exc_info.value)
    assert exc_info.value.issues[0].sheet == "BadSheet"


def test_import_skips_non_data_sheets_when_valid_rows_exist() -> None:
    workbook = _workbook_bytes(
        {
            "Cover": pd.DataFrame([{"Notes": "Export generated by CMDB"}]),
            "Apps": _valid_frame("APP-902", "Claims Hub", "Claims"),
        }
    )

    result = import_excel_workbook(workbook, selected_sheets=["Cover", "Apps"])

    assert result.row_count == 1
    assert result.sheets == ["Apps"]
    assert result.rows[0]["app_id"] == "APP-902"
    assert result.warnings
    assert result.warnings[0].sheet == "Cover"


def test_import_defaults_nonessential_columns_and_generates_ids() -> None:
    workbook = _workbook_bytes(
        {
            "North Region": pd.DataFrame(
                [
                    {
                        "Service": "Identity Vault",
                        "LOB": "Identity",
                        "Region": "SLC-1",
                        "Baseline": "2026.04",
                        "Installed Version": "2025.12",
                        "Criticality": "Mission Critical",
                    }
                ]
            )
        }
    )

    result = import_excel_workbook(workbook, selected_sheets=["North Region"])
    row = result.rows[0]

    assert row["app_id"].startswith("NORTH-REGION-")
    assert row["app_name"] == "Identity Vault"
    assert row["status"] == "Open"
    assert row["exemption_requested"] == "N"
    assert row["in_scope"] == "Y"
    assert row["rto_score"] == 1
    assert row["drift_detected_on"]


def test_imports_normalized_applications_and_drift_instances_workbook() -> None:
    workbook = _workbook_bytes(
        {
            "Applications": pd.DataFrame(
                [
                    {
                        "app_id": "APP-100",
                        "app_name": "Payments Core",
                        "app_owner": "Maya Rivera",
                        "owner_email": "maya@example.com",
                        "owner_team": "Payments Ops",
                        "resiliency_lead": "Ishan Patel",
                        "lob": "Payments",
                        "app_status": "Active",
                        "deploy_status": "Production",
                        "in_scope": "Y",
                        "rto_score": 2,
                        "rto_hours": 4,
                        "primary_dc": "DAL-1",
                        "secondary_dc": "PHX-2",
                        "env": "Prod",
                        "hosting": "Private Cloud",
                        "os_family": "Linux",
                        "last_test_date": "2026-01-01",
                        "last_test_result": "Pass",
                    }
                ]
            ),
            "Drift Instances": pd.DataFrame(
                [
                    {
                        "drift_id": "DR-1",
                        "app_id": "APP-100",
                        "lob": "Payments",
                        "rto_score": 2,
                        "rto_hours": 4,
                        "resiliency_lead": "Ishan Patel",
                        "primary_dc": "DAL-1",
                        "secondary_dc": "PHX-2",
                        "product_category": "Payments",
                        "product": "Payment Gateway",
                        "instance_name": "pay-core-01",
                        "approved_version": "2026.04",
                        "detected_version": "2025.12",
                        "status": "Open",
                        "drift_open_date": "2026-02-01",
                        "drift_close_date": None,
                        "drift_duration_days": 120,
                        "exemption_requested": "Y",
                        "exemption_result": "Pending",
                        "root_cause": "Patch backlog",
                        "environment": "Prod",
                    },
                    {
                        "drift_id": "DR-2",
                        "app_id": "APP-100",
                        "lob": "Payments",
                        "rto_score": 3,
                        "rto_hours": 8,
                        "resiliency_lead": "Ishan Patel",
                        "primary_dc": "DAL-1",
                        "secondary_dc": "PHX-2",
                        "product_category": "Payments",
                        "product": "Payment Gateway",
                        "instance_name": "pay-core-02",
                        "approved_version": "11.0",
                        "detected_version": "10.8",
                        "status": "Open",
                        "drift_open_date": "2026-03-15",
                        "drift_close_date": None,
                        "drift_duration_days": 78,
                        "exemption_requested": "N",
                        "exemption_result": None,
                        "root_cause": "Image lag",
                        "environment": "Prod",
                    },
                ]
            ),
            "Drift Notes": pd.DataFrame(
                [
                    {
                        "note_id": "N-1",
                        "drift_id": "DR-1",
                        "app_id": "APP-100",
                        "note_date": "2026-04-01",
                        "note_type": "Escalation",
                        "author_role": "Risk",
                        "note_text": "Requires VP attention.",
                        "escalation_flag": "Y",
                    }
                ]
            ),
        }
    )

    preview = preview_excel_workbook(workbook)
    assert {row["sheet"]: row["import_role"] for row in preview} == {
        "Applications": "Application metadata",
        "Drift Instances": "Drift instance rows",
        "Drift Notes": "Drift note evidence",
    }

    result = import_excel_workbook(workbook, filename="normalized.xlsx")

    assert result.row_count == 2
    assert result.sheets == ["Applications", "Drift Notes", "Drift Instances"]
    assert {row["finding_id"] for row in result.rows} == {"APP-100-DR-1", "APP-100-DR-2"}
    assert {row["app_id"] for row in result.rows} == {"APP-100"}
    assert {row["drift_id"] for row in result.rows} == {"DR-1", "DR-2"}
    first = result.rows[0]
    assert first["app_name"] == "Payments Core"
    assert first["business_owner"] == "Maya Rivera"
    assert first["technology_owner"] == "Ishan Patel"
    assert first["product"] == "Payment Gateway"
    assert first["data_center"] == "DAL-1"
    assert first["drift_detected_on"] == "2026-02-01"
    assert first["exemption_requested"] == "Y"
    assert first["exemption_result"] == "Pending"
    assert first["note_count"] == 1
    assert first["latest_note_date"] == "2026-04-01"
    assert first["latest_note_type"] == "Escalation"
    assert first["latest_note_author_role"] == "Risk"
    assert first["latest_note_text"] == "Requires VP attention."
    assert first["escalation_flag"] == "Y"
    assert not any("Missing essential columns" in warning.message for warning in result.warnings)


def test_imports_csv_as_single_sheet() -> None:
    csv_file = _csv_bytes(_valid_frame("APP-950", "Billing Core", "Finance"))

    assert list_excel_sheets(csv_file, filename="drift.csv") == ["CSV Upload"]
    preview = preview_excel_workbook(csv_file, filename="drift.csv")
    result = import_excel_workbook(csv_file, filename="drift.csv")

    assert preview[0]["import_role"] == "Standalone drift rows"
    assert result.row_count == 1
    assert result.sheets == ["CSV Upload"]
    assert result.rows[0]["app_id"] == "APP-950"


def test_uploaded_rows_refresh_database_and_feed_analytics(demo_db_path: Path) -> None:
    workbook = _workbook_bytes(
        {
            "Wave1": _valid_frame("APP-910", "Executive Ledger", "Finance"),
            "Wave2": _valid_frame("APP-911", "Claims Bridge", "Claims"),
        }
    )
    result = import_excel_workbook(workbook, selected_sheets=["Wave1", "Wave2"])

    replaced = replace_applications_rows(demo_db_path, result.rows)
    response = run_query_plan(DriftDatabase(demo_db_path), ai_risk_intelligence())

    assert replaced == 2
    assert response.error is None
    assert {row["app_id"] for row in response.rows} == {"APP-910", "APP-911"}
