"""Deterministic demo data for the drift analytics app."""

from __future__ import annotations

from datetime import date, datetime, timedelta, timezone
from typing import Any


def _days_ago(reference_date: date, days: int) -> str:
    return (reference_date - timedelta(days=days)).isoformat()


def build_demo_rows(reference_date: date | None = None) -> list[dict[str, Any]]:
    """Build realistic portfolio demo rows relative to a reference date."""

    today = reference_date or date.today()
    scanned_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat()

    rows = [
        {
            "app_id": "APP-001",
            "app_name": "Payments Gateway",
            "business_owner": "Avery Brooks",
            "technology_owner": "Priya Nair",
            "product": "Payments",
            "data_center": "DAL-1",
            "approved_version": "12.4.1",
            "detected_version": "12.1.0",
            "rto_score": 1,
            "status": "Open",
            "exemption_requested": "Y",
            "exemption_result": "Pending",
            "in_scope": "Y",
            "drift_detected_on": _days_ago(today, 132),
            "last_scanned_at": scanned_at,
        },
        {
            "app_id": "APP-002",
            "app_name": "Claims Intake",
            "business_owner": "Morgan Lee",
            "technology_owner": "Diego Silva",
            "product": "Claims",
            "data_center": "PHX-2",
            "approved_version": "8.8.0",
            "detected_version": "8.8.0",
            "rto_score": 3,
            "status": "Closed",
            "exemption_requested": "N",
            "exemption_result": None,
            "in_scope": "Y",
            "drift_detected_on": _days_ago(today, 24),
            "last_scanned_at": scanned_at,
        },
        {
            "app_id": "APP-003",
            "app_name": "Customer Identity",
            "business_owner": "Jules Turner",
            "technology_owner": "Samira Khan",
            "product": "Identity",
            "data_center": "DAL-1",
            "approved_version": "2025.11",
            "detected_version": "2025.06",
            "rto_score": 2,
            "status": "Open",
            "exemption_requested": "N",
            "exemption_result": None,
            "in_scope": "Y",
            "drift_detected_on": _days_ago(today, 96),
            "last_scanned_at": scanned_at,
        },
        {
            "app_id": "APP-004",
            "app_name": "Ledger Reconciliation",
            "business_owner": "Taylor Chen",
            "technology_owner": "Nora Patel",
            "product": "Finance",
            "data_center": "EWR-1",
            "approved_version": "5.7.2",
            "detected_version": "5.2.9",
            "rto_score": 4,
            "status": "Open",
            "exemption_requested": "Y",
            "exemption_result": "Denied",
            "in_scope": "Y",
            "drift_detected_on": _days_ago(today, 74),
            "last_scanned_at": scanned_at,
        },
        {
            "app_id": "APP-005",
            "app_name": "Partner API Hub",
            "business_owner": "Quinn Adams",
            "technology_owner": "Riley Stone",
            "product": "Integration",
            "data_center": "DAL-1",
            "approved_version": "3.10.0",
            "detected_version": "3.9.4",
            "rto_score": 5,
            "status": "Open",
            "exemption_requested": "Y",
            "exemption_result": "Approved",
            "in_scope": "Y",
            "drift_detected_on": _days_ago(today, 62),
            "last_scanned_at": scanned_at,
        },
        {
            "app_id": "APP-006",
            "app_name": "Agent Desktop",
            "business_owner": "Harper Wells",
            "technology_owner": "Noah Singh",
            "product": "Contact Center",
            "data_center": "PHX-2",
            "approved_version": "22.0.3",
            "detected_version": "21.8.1",
            "rto_score": 6,
            "status": "Open",
            "exemption_requested": "N",
            "exemption_result": None,
            "in_scope": "Y",
            "drift_detected_on": _days_ago(today, 41),
            "last_scanned_at": scanned_at,
        },
        {
            "app_id": "APP-007",
            "app_name": "Marketing Studio",
            "business_owner": "Casey Flynn",
            "technology_owner": "Amara Okafor",
            "product": "Marketing",
            "data_center": "EWR-1",
            "approved_version": "10.4",
            "detected_version": "10.1",
            "rto_score": 8,
            "status": "Open",
            "exemption_requested": "N",
            "exemption_result": None,
            "in_scope": "N",
            "drift_detected_on": _days_ago(today, 119),
            "last_scanned_at": scanned_at,
        },
        {
            "app_id": "APP-008",
            "app_name": "Risk Scoring",
            "business_owner": "Blake Morgan",
            "technology_owner": "Iris Romero",
            "product": "Risk",
            "data_center": "DAL-1",
            "approved_version": "7.5.0",
            "detected_version": "7.0.2",
            "rto_score": 2,
            "status": "Open",
            "exemption_requested": "Y",
            "exemption_result": "Pending",
            "in_scope": "Y",
            "drift_detected_on": _days_ago(today, 121),
            "last_scanned_at": scanned_at,
        },
        {
            "app_id": "APP-009",
            "app_name": "Policy Admin",
            "business_owner": "Rowan Price",
            "technology_owner": "Elliot Grant",
            "product": "Policy",
            "data_center": "PHX-2",
            "approved_version": "6.0.0",
            "detected_version": "5.9.8",
            "rto_score": 3,
            "status": "Open",
            "exemption_requested": "N",
            "exemption_result": None,
            "in_scope": "Y",
            "drift_detected_on": _days_ago(today, 88),
            "last_scanned_at": scanned_at,
        },
        {
            "app_id": "APP-010",
            "app_name": "Document Archive",
            "business_owner": "Devon Hart",
            "technology_owner": "Mina Park",
            "product": "Records",
            "data_center": "EWR-1",
            "approved_version": "4.4.0",
            "detected_version": "4.4.0",
            "rto_score": 7,
            "status": "Closed",
            "exemption_requested": "N",
            "exemption_result": None,
            "in_scope": "Y",
            "drift_detected_on": _days_ago(today, 18),
            "last_scanned_at": scanned_at,
        },
        {
            "app_id": "APP-011",
            "app_name": "Fraud Workbench",
            "business_owner": "Emerson Reed",
            "technology_owner": "Sofia Ortiz",
            "product": "Risk",
            "data_center": "DAL-1",
            "approved_version": "9.12.0",
            "detected_version": "9.8.7",
            "rto_score": 1,
            "status": "Open",
            "exemption_requested": "N",
            "exemption_result": None,
            "in_scope": "Y",
            "drift_detected_on": _days_ago(today, 37),
            "last_scanned_at": scanned_at,
        },
        {
            "app_id": "APP-012",
            "app_name": "HR Case Manager",
            "business_owner": "Kendall Shaw",
            "technology_owner": "Theo Martin",
            "product": "People",
            "data_center": "SLC-1",
            "approved_version": "2.6.1",
            "detected_version": "2.4.0",
            "rto_score": 6,
            "status": "Open",
            "exemption_requested": "Y",
            "exemption_result": "Approved",
            "in_scope": "Y",
            "drift_detected_on": _days_ago(today, 107),
            "last_scanned_at": scanned_at,
        },
    ]
    for row in rows:
        row.setdefault("finding_id", row["app_id"])
        row.setdefault("drift_id", None)
        row.setdefault("note_count", 0)
        row.setdefault("latest_note_date", None)
        row.setdefault("latest_note_type", None)
        row.setdefault("latest_note_author_role", None)
        row.setdefault("latest_note_text", None)
        row.setdefault("escalation_flag", None)
    return rows
